sudo: false

language: node_js

node_js:
  - "6"

before_install:
  - npm install -g yarn
  - yarn install
cache:
  yarn: true
  directories:
    - node_modules

script: yarn run generate

after_success:
  - bash ./deploy.sh
