sudo: false

language: node_js

node_js:
  - "7"

before_install:
  - npm install -g yarn
cache:
  yarn: true
  directories:
    - node_modules

script: yarn run build

after_success:
  - bash ./deploy.sh
